// Built-in function signatures and one-line docs, for completion and hover.
export const FUNCTION_DOCS = {
  "contains": ["contains(element, sequence)", "True if the array, object (key) or string contains the element."],
  "size": ["size(sequence)", "Length of an array or string, number of keys of an object."],
  "error": ["error(message)", "Aborts the transform with the given message."],
  "min": ["min(a, b)", "The smaller of two values."],
  "max": ["max(a, b)", "The larger of two values."],
  "is-number": ["is-number(value)", "True if the value is a number."],
  "is-integer": ["is-integer(value)", "True if the value is an integer."],
  "is-decimal": ["is-decimal(value)", "True if the value is a decimal number."],
  "number": ["number(value [, fallback])", "Parses a string into a number; returns the fallback (or fails) if it is not one."],
  "round": ["round(number)", "Rounds to the nearest integer."],
  "floor": ["floor(number)", "Rounds down to an integer."],
  "ceiling": ["ceiling(number)", "Rounds up to an integer."],
  "random": ["random()", "A random number between 0 and 1."],
  "sum": ["sum(array)", "Sum of the numbers in an array."],
  "mod": ["mod(dividend, divisor)", "Modulo; the result takes the sign of the divisor."],
  "hash-int": ["hash-int(value)", "A hash of the value as an integer."],
  "is-string": ["is-string(value)", "True if the value is a string."],
  "string": ["string(value)", "Converts any value to a string."],
  "test": ["test(input, regex)", "True if the regular expression matches the string."],
  "capture": ["capture(input, regex)", "Object of the named groups captured by the regular expression."],
  "split": ["split(string, regex)", "Splits a string into an array on a regular expression."],
  "join": ["join(array, separator)", "Joins an array of strings with a separator."],
  "lowercase": ["lowercase(string)", "Lower-cases a string."],
  "uppercase": ["uppercase(string)", "Upper-cases a string."],
  "sha256-hex": ["sha256-hex(string)", "SHA-256 of the string as hex."],
  "starts-with": ["starts-with(string, prefix)", "True if the string starts with the prefix."],
  "ends-with": ["ends-with(string, suffix)", "True if the string ends with the suffix."],
  "from-json": ["from-json(string [, fallback])", "Parses a JSON string; returns the fallback (or fails) if it is invalid."],
  "to-json": ["to-json(value)", "Serialises a value to a JSON string."],
  "replace": ["replace(input, regex, replacement)", "Replaces every regex match in the string."],
  "trim": ["trim(string)", "Removes leading and trailing whitespace."],
  "uuid": ["uuid([a, b])", "A random UUID; with two numbers, a deterministic one."],
  "not": ["not(value)", "Boolean negation."],
  "boolean": ["boolean(value)", "Converts to boolean: false, null, 0, empty string/array/object are false."],
  "is-boolean": ["is-boolean(value)", "True if the value is a boolean."],
  "is-object": ["is-object(value)", "True if the value is an object."],
  "get-key": ["get-key(object, key [, fallback])", "Value of a key, for keys only known at runtime."],
  "array": ["array(value)", "Converts an object to an array of {key, value}; arrays are returned as they are."],
  "is-array": ["is-array(value)", "True if the value is an array."],
  "flatten": ["flatten(array)", "Flattens nested arrays one level."],
  "all": ["all(array)", "True if every element is true."],
  "any": ["any(array)", "True if any element is true."],
  "zip": ["zip(array1, array2)", "Pairs elements of two arrays into an array of two-element arrays."],
  "zip-with-index": ["zip-with-index(array)", "Array of {value, index} for each element."],
  "index-of": ["index-of(array, value)", "Index of the first occurrence, or -1."],
  "now": ["now()", "The current time as seconds since the epoch."],
  "parse-time": ["parse-time(string, format [, fallback])", "Parses a time string with a Java-style pattern into epoch seconds."],
  "format-time": ["format-time(timestamp, format [, timezone])", "Formats epoch seconds with a Java-style pattern."],
  "parse-url": ["parse-url(string)", "Splits a URL into scheme, host, port, path, query and fragment."],
  "fallback": ["fallback(a, b, ...)", "The first argument that is not null, empty or false-like."],
};

export const KEYWORDS = ["let", "def", "if", "else", "for", "import", "as", "and", "or"];
export const CONSTANTS = ["true", "false", "null"];
